### ISSUE TITLE
Error with com.landawn.abacus.logging.JDKLogger log

### ISSUE THREAD

**Issue by kreecha** [landawn/AbacusUtil#5] opened 2017-10-28 03:02 UTC
Your product seems interesting and it can be useful i can see from the features. However, I downloaded your library (all - 1.0.3.jar) to be used locally and even via Maven repo. I faced the following errors when running using Mavan or local:

Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class com.landawn.abacus.parser.JSONParserImpl
	at com.landawn.abacus.parser.ParserFactory.createJSONParser(ParserFactory.java:194)
	at com.landawn.abacus.util.CSVUtil.<clinit>(CSVUtil.java:69)
	at util.ActIDActNameSrcIpTime.TestAbacus.main(TestAbacus.java:24)

The code in TestAbacus.java is below:

`import com.landawn.abacus.DataSet;
import com.landawn.abacus.util.CSVUtil;
import java.io.File;

public class TestAbacus {

    public static void main(String args[]) {
        File file = new File("C:\\Projects\\Java\\UserProfile\\data\\Sep_Coumn_1000.csv");
        DataSet dataset = CSVUtil.loadCSV(file);
   }
}
`
I used Java jdk1.8.0_141 running on NetBeans IDE 8.1 (Build 201510222201). I hope i can try out your project it seems powerful.

Regards,
KP

**Comment by landawn** [comment] 2017-10-29 00:13
It's a bug. The root cause is the JSONParserImpl class isn't initialized successfully due to the cycling dependence between it and class N. It's fixed in  version 1.0.5. please download the new version and let me know if you have further questions.

Thank you for reporting the issue and I hope you will enjoy using the library.

**Comment by kreecha** [comment] 2017-10-29 05:22
Hi there
Thank you for the respond and fix, but found the new error is thrown as below. At least it is not the same so i can see i will be able to use your software soon :-)

Oct 29, 2017 12:15:06 PM com.landawn.abacus.logging.JDKLogger log
INFO: Initialized with JDK Logger
Exception in thread "main" java.lang.ArrayStoreException: java.util.ArrayList
	at com.landawn.abacus.parser.JSONParserImpl.readArray(Unknown Source)
	at com.landawn.abacus.parser.JSONParserImpl.readString(Unknown Source)
	at com.landawn.abacus.parser.JSONParserImpl.readString(Unknown Source)
	at com.landawn.abacus.parser.AbstractJSONParser.readString(Unknown Source)
	at com.landawn.abacus.util.CSVUtil.loadCSV(CSVUtil.java:195)
	at com.landawn.abacus.util.CSVUtil.loadCSV(CSVUtil.java:134)
	at com.landawn.abacus.util.CSVUtil.loadCSV(CSVUtil.java:100)
	at com.landawn.abacus.util.CSVUtil.loadCSV(CSVUtil.java:80)
	at com.landawn.abacus.util.CSVUtil.loadCSV(CSVUtil.java:76)
	at com.landawn.abacus.util.CSVUtil.loadCSV(CSVUtil.java:72)
	at util.ActIDActNameSrcIpTime.TestAbacus.main(TestAbacus.java:20)

**Comment by landawn** [comment] 2017-10-29 05:36
Could you please show me your test code and couple of lines of the sample CSV file? so i can find out the root cause?

**Comment by kreecha** [comment] 2017-10-29 06:27
Hi there,

Yes sure. Here is the code and the file attached i used to test your
library.

Thank you
KP

-------------------------------------------------------

package util.ActIDActNameSrcIpTime;

import com.landawn.abacus.DataSet;
import com.landawn.abacus.util.CSVUtil;
import java.io.File;

/**
 *
 * @author userhp
 */
public class TestAbacus {

    public static void main(String args[]) {
        File file = new
File("C:\\Projects\\Java\\UserProfile\\data\\Sep_RIB_Minus_Four_Coumn_1000_NoUnderscore.csv");
        DataSet dataset = CSVUtil.loadCSV(file);
   }

}

-------------------------------------------------------

**Comment by landawn** [comment] 2017-10-29 07:00
Thanks! i didn't find the attached CSV file you used for test for some reason. Can you please check it for me or upload it again if it's missed?

**Comment by kreecha** [comment] 2017-10-29 15:04
Hi
Very strange here i retried. Thanks again for your help.KP

Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: kreecha puphaiboon <puphaiboon.kreecha@gmail.com> Date: 29/10/2017  13:27  (GMT+07:00) To: landawn/AbacusUtil <reply@reply.github.com> Subject: Re: [landawn/AbacusUtil] Error with com.landawn.abacus.logging.JDKLogger log (#5) 
Hi there,
Yes sure. Here is the code and the file attached i used to test your library. 
Thank youKP
-------------------------------------------------------
package util.ActIDActNameSrcIpTime;
import com.landawn.abacus.DataSet;import com.landawn.abacus.util.CSVUtil;import java.io.File;
/** * * @author userhp */public class TestAbacus {
    public static void main(String args[]) {        File file = new File("C:\\Projects\\Java\\UserProfile\\data\\Sep_RIB_Minus_Four_Coumn_1000_NoUnderscore.csv");        DataSet dataset = CSVUtil.loadCSV(file);   }
} 
-------------------------------------------------------

On Sun, Oct 29, 2017 at 12:36 PM, landawn <notifications@github.com> wrote:
Could you please show me your test code and couple of lines of the sample CSV file? so i can find out the root cause?

**Comment by landawn** [comment] 2017-10-29 15:49
Below format is not supported currently, 
```csv
firstName, lastName, numbers
jack, chen, [2, 2, 2, 3]
```
you need to quote the array column with ".
```csv
firstName, lastName, numbers
jack, chen, "[2, 2, 2, 3]"
```

**Closed** 2017-10-31 18:46 UTC
